name: build

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.x', '3.7', '3.8', '3.9', '3.10', '3.11']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Pip install basic
        run: pip install --upgrade pip build setuptools
      - name: Pip install requirements
        run: pip install -r requirements.txt
      - name: build package
        run: python3 -m build -nwx .
      - name: Run tests
        run: python -m unittest
